import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Layout from "./layout";
// import SimpleCard from "./flashcard/simple-card";
// import InputCard from "./flashcard/form-card";
// import MultipleChoice from "./flashcard/multiple-choice-card";
// import panelQuestion from "./public/data/questionAndAnswer"

export default function Home() {
  return (
    <div className={styles.container}>
      <Layout>
        <Head>
          <title>My FlashCard next app website</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <nav> </nav>
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to my first blog next app !</h1>
          <br />
          <br />
          <ul>
            <li>
              <Link href="/flashcard/simple-card">Simple-card</Link>
            </li>
            <li>
              <Link href="/flashcard/form-card">Form-card</Link>
            </li>
            <li>
              <Link href="/flashcard/multiple-choice-card">
                Multiple-choice-card
              </Link>
            </li>
          </ul>

          <p className={styles.description}>
            Hello, je suis Kevin ! Bienvenue sur mon site de FlashCard. Bonne
            découverte et bon jeux :)
            <code className={styles.code}></code>
          </p>
        </main>

        <footer className={styles.footer}>
          <a target="_blank" rel="noopener noreferrer">
            Powered by{" Kevin"}
            <span className={styles.logo}></span>
          </a>
        </footer>
      </Layout>
    </div>
  );
}
